export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const GET_CONTACTS = 'GET_CONTACT';
export const CONTACTS_LOADING = 'CONTACTS_LOADING';
